from pathlib import Path
p=Path('src/html.ts')
s=p.read_text()
s=s.replace("    #partEffects = new Map<Runtime, EffectUnSubscriber>()", "    #partEffects?: Map<Runtime, EffectUnSubscriber>")
s=s.replace("    __CHILDREN__: Set<HtmlTemplate> = new Set()", "    #children?: Set<HtmlTemplate>\n\n    get __CHILDREN__(): Set<HtmlTemplate> {\n        return (this.#children ??= new Set())\n    }")
s=s.replace("        this.#partEffects.get(part)?.()\n        this.#partEffects.delete(part)", "        this.#partEffects?.get(part)?.()\n        this.#partEffects?.delete(part)")
s=s.replace("            this.#partEffects.set(part, effect(commit))", "            ;(this.#partEffects ??= new Map()).set(part, effect(commit))")
s=s.replace("        this.#partEffects.clear()", "        this.#partEffects?.clear()")
s=s.replace("        for (const unsub of this.#partEffects.values()) unsub()", "        for (const unsub of this.#partEffects?.values() ?? []) unsub()")
p.write_text(s)
